### ISSUE TITLE
Error in SDCARD_GetBlocksNumber

### ISSUE THREAD

**Issue by borodaxel** [afiskon/stm32-sdcard#1]
SDCARD_GetBlocksNumber returns the size which is twice bigger than actual.

To multiply by 512 the tmp variable should be left-shifted by 9 bits, not 10.

**Comment by afiskon** [comment]
Thanks, fixed https://github.com/afiskon/stm32-sdcard/commit/7badb3eeb1a52e4f47cebc3cacc61455651e1ec7
