### ISSUE TITLE
WaitNotBusy() doesn't always succeed on init

### ISSUE THREAD

**Issue by petertorelli** [afiskon/stm32-sdcard#4]
SDCARD_Init() calls WaitNotBusy() after deasserting CS (after sending 80 bits).

There is a problem here: not all cards go to 0xFF on first insert. These cards must first receive CMD0. Then they will write 0xFF to DO.

The solution is to add a timeout to WaitNotReady and let the caller decide what to do if SDCARD_ReadR1 fails. Execution should not depend on WaitNotReady explicity. I discovered this when trying to understand why the Arduino SD lib worked on some of my cards, but STM32FatFs + SDCARD failed.

This fixes your code to work with these cards (which is literally all of my SD Micro cards):

```C
/**
 * ptorelli - this should not return an error, the calling function should
 * ptorelli - when booting, not all cards go to this state. It requires CMDD0,
 * ptorelli - so waiting for 0xff w/o CMD0 will always fail.
 */
static int SDCARD_WaitNotBusy(void) {
    uint32_t timeoutMsec = 300; // ptorelli - should be a parameter
    uint8_t busy;
    uint32_t t0;
    uint32_t dt;
    t0 = HAL_GetTick(); // assuming msec
    do {
        if(SDCARD_ReadBytes(&busy, sizeof(busy)) < 0) {
            return -1;
        }
        if (busy == 0xff) {
          break;
        }
        dt = HAL_GetTick() - t0;
    } while(dt < timeoutMsec);

    return 0;
}
```

Can I submit a PR?

**Comment by afiskon** [comment]
@petertorelli thanks for the report.

I'm not 100% sure if that the proposed fix is the correct one though. 

Could you please check if simply sending CMD0 between steps 1 and 2 (step 1.5 :) in SDCARD_Init() will work for all the cards? If it does, a suggest modifying SDCARD_Init() accordingly instead and keeping SDCARD_WaitNotBusy() as is.

**Comment by petertorelli** [comment]
@afiskon ah, that works.

What are your thoughts on timeouts for the Wait* and Read* functions? Stalling in an infinite loop is hard to respond to. Obviously, it would change the code significantly. However a substantially large timeout (5 seconds) should cover all cases.

**Comment by afiskon** [comment]
@petertorelli I believe it very much depends on the application. In my case the SD card was a part of the device and was expected not to timeout. In case if somehow it did there was no reasonable way to handle the error anyway and hanging was a reasonable thing to do.

However, I can imagine how in different applications it would make sense to check for a timeout. I will not mind modifying the API and introducing a timeout argument to all the public procedures, as long as specifying an infinite timeout will be possible. Alternatively, the API can be kept as is and the timeout specifying as a macro.

**Comment by petertorelli** [comment]
Closing this because I don't have free time to make progress. Thanks tho!
